# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonDepositar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDepositar.setGeometry(QtCore.QRect(30, 20, 101, 31))
        self.buttonDepositar.setObjectName("buttonDepositar")
        self.buttonSacar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSacar.setGeometry(QtCore.QRect(30, 60, 101, 31))
        self.buttonSacar.setObjectName("buttonSacar")
        self.buttonTransferir = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTransferir.setGeometry(QtCore.QRect(30, 100, 101, 31))
        self.buttonTransferir.setObjectName("buttonTransferir")
        self.buttonUsuario = QtWidgets.QPushButton(self.centralwidget)
        self.buttonUsuario.setGeometry(QtCore.QRect(30, 140, 101, 31))
        self.buttonUsuario.setObjectName("buttonUsuario")
        self.buttonVoltar_5 = QtWidgets.QPushButton(self.centralwidget)
        self.buttonVoltar_5.setGeometry(QtCore.QRect(30, 180, 101, 31))
        self.buttonVoltar_5.setObjectName("buttonVoltar_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 20, 61, 41))
        self.label.setObjectName("label")
        self.slotSaldo = QtWidgets.QLabel(self.centralwidget)
        self.slotSaldo.setGeometry(QtCore.QRect(530, 20, 61, 41))
        self.slotSaldo.setText("")
        self.slotSaldo.setObjectName("slotSaldo")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(435, 10, 31, 61))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(450, 55, 171, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(450, 0, 171, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(600, 10, 41, 61))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonDepositar.setText(_translate("MainWindow", "Depositar"))
        self.buttonSacar.setText(_translate("MainWindow", "Sacar"))
        self.buttonTransferir.setText(_translate("MainWindow", "Transferir"))
        self.buttonUsuario.setText(_translate("MainWindow", "Usuário"))
        self.buttonVoltar_5.setText(_translate("MainWindow", "Sair"))
        self.label.setText(_translate("MainWindow", "Saldo: R$"))
