# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaSacar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCadastrar.setGeometry(QtCore.QRect(240, 80, 81, 23))
        self.buttonCadastrar.setObjectName("buttonCadastrar")
        self.labelSenha = QtWidgets.QLabel(self.centralwidget)
        self.labelSenha.setGeometry(QtCore.QRect(20, 50, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelSenha.setFont(font)
        self.labelSenha.setObjectName("labelSenha")
        self.lineSenha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSenha.setGeometry(QtCore.QRect(70, 50, 251, 20))
        self.lineSenha.setObjectName("lineSenha")
        self.buttonVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonVoltar.setGeometry(QtCore.QRect(150, 80, 81, 23))
        self.buttonVoltar.setObjectName("buttonVoltar")
        self.labelValor = QtWidgets.QLabel(self.centralwidget)
        self.labelValor.setGeometry(QtCore.QRect(20, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelValor.setFont(font)
        self.labelValor.setObjectName("labelValor")
        self.lineValor = QtWidgets.QLineEdit(self.centralwidget)
        self.lineValor.setGeometry(QtCore.QRect(70, 20, 251, 20))
        self.lineValor.setObjectName("lineValor")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Saque"))
        self.buttonCadastrar.setText(_translate("MainWindow", "Sacar"))
        self.labelSenha.setText(_translate("MainWindow", "Senha:"))
        self.buttonVoltar.setText(_translate("MainWindow", "Voltar"))
        self.labelValor.setText(_translate("MainWindow", "Valor :"))
