# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 478)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelCpf = QtWidgets.QLabel(self.centralwidget)
        self.labelCpf.setGeometry(QtCore.QRect(20, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelCpf.setFont(font)
        self.labelCpf.setObjectName("labelCpf")
        self.lineCpf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineCpf.setGeometry(QtCore.QRect(60, 20, 261, 20))
        self.lineCpf.setObjectName("lineCpf")
        self.labelSenha = QtWidgets.QLabel(self.centralwidget)
        self.labelSenha.setGeometry(QtCore.QRect(20, 50, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelSenha.setFont(font)
        self.labelSenha.setObjectName("labelSenha")
        self.lineSenha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSenha.setGeometry(QtCore.QRect(70, 50, 251, 20))
        self.lineSenha.setObjectName("lineSenha")
        self.buttonCadastre = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCadastre.setGeometry(QtCore.QRect(240, 80, 81, 23))
        self.buttonCadastre.setObjectName("buttonCadastre")
        self.buttonVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonVoltar.setGeometry(QtCore.QRect(150, 80, 81, 23))
        self.buttonVoltar.setObjectName("buttonVoltar")
        self.buttonSair = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSair.setGeometry(QtCore.QRect(60, 80, 81, 23))
        self.buttonSair.setObjectName("buttonSair")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelCpf.setText(_translate("MainWindow", "CPF:"))
        self.labelSenha.setText(_translate("MainWindow", "Senha:"))
        self.buttonCadastre.setText(_translate("MainWindow", "Cadastre-se"))
        self.buttonVoltar.setText(_translate("MainWindow", "Entrar"))
        self.buttonSair.setText(_translate("MainWindow", "Sair"))
