# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaCadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaCadastro(object):
    def setupUi(self, TelaCadastro):
        TelaCadastro.setObjectName("TelaCadastro")
        TelaCadastro.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(TelaCadastro)
        self.centralwidget.setObjectName("centralwidget")
        self.labelNome = QtWidgets.QLabel(self.centralwidget)
        self.labelNome.setGeometry(QtCore.QRect(30, 30, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelNome.setFont(font)
        self.labelNome.setObjectName("labelNome")
        self.labelCpf = QtWidgets.QLabel(self.centralwidget)
        self.labelCpf.setGeometry(QtCore.QRect(30, 60, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelCpf.setFont(font)
        self.labelCpf.setObjectName("labelCpf")
        self.labelEndereco = QtWidgets.QLabel(self.centralwidget)
        self.labelEndereco.setGeometry(QtCore.QRect(30, 90, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelEndereco.setFont(font)
        self.labelEndereco.setObjectName("labelEndereco")
        self.labelData = QtWidgets.QLabel(self.centralwidget)
        self.labelData.setGeometry(QtCore.QRect(30, 120, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelData.setFont(font)
        self.labelData.setObjectName("labelData")
        self.labelSenha = QtWidgets.QLabel(self.centralwidget)
        self.labelSenha.setGeometry(QtCore.QRect(30, 150, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelSenha.setFont(font)
        self.labelSenha.setObjectName("labelSenha")
        self.lineNome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineNome.setGeometry(QtCore.QRect(80, 30, 251, 20))
        self.lineNome.setObjectName("lineNome")
        self.lineCpf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineCpf.setGeometry(QtCore.QRect(70, 60, 261, 20))
        self.lineCpf.setObjectName("lineCpf")
        self.lineEndereco = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEndereco.setGeometry(QtCore.QRect(100, 90, 231, 20))
        self.lineEndereco.setObjectName("lineEndereco")
        self.lineData = QtWidgets.QLineEdit(self.centralwidget)
        self.lineData.setGeometry(QtCore.QRect(170, 120, 161, 20))
        self.lineData.setObjectName("lineData")
        self.lineSenha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSenha.setGeometry(QtCore.QRect(80, 150, 251, 20))
        self.lineSenha.setObjectName("lineSenha")
        self.buttonVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonVoltar.setGeometry(QtCore.QRect(160, 180, 81, 23))
        self.buttonVoltar.setObjectName("buttonVoltar")
        self.buttonCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCadastrar.setGeometry(QtCore.QRect(250, 180, 81, 23))
        self.buttonCadastrar.setObjectName("buttonCadastrar")
        TelaCadastro.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaCadastro)
        self.statusbar.setObjectName("statusbar")
        TelaCadastro.setStatusBar(self.statusbar)

        self.retranslateUi(TelaCadastro)
        QtCore.QMetaObject.connectSlotsByName(TelaCadastro)

    def retranslateUi(self, TelaCadastro):
        _translate = QtCore.QCoreApplication.translate
        TelaCadastro.setWindowTitle(_translate("TelaCadastro", "MainWindow"))
        self.labelNome.setText(_translate("TelaCadastro", "Nome:"))
        self.labelCpf.setText(_translate("TelaCadastro", "CPF:"))
        self.labelEndereco.setText(_translate("TelaCadastro", "Endereco:"))
        self.labelData.setText(_translate("TelaCadastro", "Data de Nascimento:"))
        self.labelSenha.setText(_translate("TelaCadastro", "Senha:"))
        self.buttonVoltar.setText(_translate("TelaCadastro", "Voltar"))
        self.buttonCadastrar.setText(_translate("TelaCadastro", "Cadastrar"))
