# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaTransferir.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineValor = QtWidgets.QLineEdit(self.centralwidget)
        self.lineValor.setGeometry(QtCore.QRect(60, 20, 251, 20))
        self.lineValor.setObjectName("lineValor")
        self.buttonVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonVoltar.setGeometry(QtCore.QRect(140, 140, 81, 23))
        self.buttonVoltar.setObjectName("buttonVoltar")
        self.buttonTransferir = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTransferir.setGeometry(QtCore.QRect(230, 140, 81, 23))
        self.buttonTransferir.setObjectName("buttonTransferir")
        self.labelSenha = QtWidgets.QLabel(self.centralwidget)
        self.labelSenha.setGeometry(QtCore.QRect(10, 50, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelSenha.setFont(font)
        self.labelSenha.setObjectName("labelSenha")
        self.lineSenha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSenha.setGeometry(QtCore.QRect(60, 50, 251, 20))
        self.lineSenha.setObjectName("lineSenha")
        self.labelValor = QtWidgets.QLabel(self.centralwidget)
        self.labelValor.setGeometry(QtCore.QRect(10, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelValor.setFont(font)
        self.labelValor.setObjectName("labelValor")
        self.labelDestino = QtWidgets.QLabel(self.centralwidget)
        self.labelDestino.setGeometry(QtCore.QRect(10, 100, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelDestino.setFont(font)
        self.labelDestino.setObjectName("labelDestino")
        self.lineDestino = QtWidgets.QLineEdit(self.centralwidget)
        self.lineDestino.setGeometry(QtCore.QRect(100, 100, 211, 20))
        self.lineDestino.setObjectName("lineDestino")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonVoltar.setText(_translate("MainWindow", "Voltar"))
        self.buttonTransferir.setText(_translate("MainWindow", "Transferir"))
        self.labelSenha.setText(_translate("MainWindow", "Senha:"))
        self.labelValor.setText(_translate("MainWindow", "Valor :"))
        self.labelDestino.setText(_translate("MainWindow", "CPF Destino:"))
