# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_telaLogin(object):
    def setupUi(self, telaLogin):
        telaLogin.setObjectName("telaLogin")
        telaLogin.resize(479, 640)
        telaLogin.setWindowOpacity(1.0)
        telaLogin.setStyleSheet(".QFrame {\n"
"    background-color: rgba(25,25,112,0.8);\n"
"}")
        self.frameLogin = QtWidgets.QFrame(telaLogin)
        self.frameLogin.setGeometry(QtCore.QRect(100, 160, 271, 221))
        self.frameLogin.setStyleSheet("\n"
".QFrame#frameLogin {\n"
"    background-color: rgba(255,250,240,0.6);\n"
"    border-radius: 1em;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(0,0,0);\n"
"}\n"
"")
        self.frameLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLogin.setObjectName("frameLogin")
        self.labelCpf = QtWidgets.QLabel(self.frameLogin)
        self.labelCpf.setGeometry(QtCore.QRect(10, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCpf.setFont(font)
        self.labelCpf.setStyleSheet(".QLabel {\n"
"    font-size: 2em;\n"
"}")
        self.labelCpf.setObjectName("labelCpf")
        self.labelSenha = QtWidgets.QLabel(self.frameLogin)
        self.labelSenha.setGeometry(QtCore.QRect(10, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelSenha.setFont(font)
        self.labelSenha.setStyleSheet(".QLabel {\n"
"    font-size: 2em;\n"
"}")
        self.labelSenha.setObjectName("labelSenha")
        self.lineSenha = QtWidgets.QLineEdit(self.frameLogin)
        self.lineSenha.setGeometry(QtCore.QRect(10, 110, 251, 31))
        self.lineSenha.setStyleSheet(".QLineEdit{\n"
"    border-radius: 0.5em;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(0,0,0);\n"
"}")
        self.lineSenha.setObjectName("lineSenha")
        self.lineCpf = QtWidgets.QLineEdit(self.frameLogin)
        self.lineCpf.setGeometry(QtCore.QRect(10, 40, 251, 31))
        self.lineCpf.setStyleSheet(".QLineEdit{\n"
"    border-radius: 0.5em;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(0,0,0);\n"
"}")
        self.lineCpf.setObjectName("lineCpf")
        self.buttonSair = QtWidgets.QPushButton(self.frameLogin)
        self.buttonSair.setGeometry(QtCore.QRect(10, 160, 71, 41))
        self.buttonSair.setStyleSheet(".QPushButton{\n"
"    background-color: rgb(75,0,130);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 0.5em;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(0,0,0);\n"
"}\n"
"\n"
".QPushButton:hover{\n"
"    background-color: rgba(75,0,130,0.6);\n"
"}")
        self.buttonSair.setObjectName("buttonSair")
        self.buttonEntrar = QtWidgets.QPushButton(self.frameLogin)
        self.buttonEntrar.setGeometry(QtCore.QRect(100, 160, 71, 41))
        self.buttonEntrar.setStyleSheet(".QPushButton{\n"
"    background-color: rgb(75,0,130);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 0.5em;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(0,0,0);\n"
"}\n"
"\n"
".QPushButton:hover{\n"
"    background-color: rgba(75,0,130,0.6);\n"
"}")
        self.buttonEntrar.setObjectName("buttonEntrar")
        self.buttonCadatre = QtWidgets.QPushButton(self.frameLogin)
        self.buttonCadatre.setGeometry(QtCore.QRect(190, 160, 71, 41))
        self.buttonCadatre.setStyleSheet(".QPushButton{\n"
"    background-color: rgb(75,0,130);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 0.5em;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(0,0,0);\n"
"}\n"
"\n"
".QPushButton:hover{\n"
"    background-color: rgba(75,0,130,0.6);\n"
"}")
        self.buttonCadatre.setObjectName("buttonCadatre")
        self.logo = QtWidgets.QLabel(telaLogin)
        self.logo.setGeometry(QtCore.QRect(150, -40, 161, 161))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(26)
        self.logo.setFont(font)
        self.logo.setStyleSheet(".QLabel#logo{\n"
"    color: rgb(255,255,255);\n"
"    text-align: rigth;\n"
"}")
        self.logo.setObjectName("logo")
        self.line = QtWidgets.QFrame(telaLogin)
        self.line.setGeometry(QtCore.QRect(0, 70, 491, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(telaLogin)
        QtCore.QMetaObject.connectSlotsByName(telaLogin)

    def retranslateUi(self, telaLogin):
        _translate = QtCore.QCoreApplication.translate
        telaLogin.setWindowTitle(_translate("telaLogin", "LOGIN"))
        self.labelCpf.setText(_translate("telaLogin", "CPF"))
        self.labelSenha.setText(_translate("telaLogin", "SENHA"))
        self.buttonSair.setText(_translate("telaLogin", "SAIR"))
        self.buttonEntrar.setText(_translate("telaLogin", "ENTRAR"))
        self.buttonCadatre.setText(_translate("telaLogin", "CADASTRAR"))
        self.logo.setText(_translate("telaLogin", "P-BANK"))
