# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaUsuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelNome = QtWidgets.QLabel(self.centralwidget)
        self.labelNome.setGeometry(QtCore.QRect(20, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelNome.setFont(font)
        self.labelNome.setObjectName("labelNome")
        self.labelData = QtWidgets.QLabel(self.centralwidget)
        self.labelData.setGeometry(QtCore.QRect(20, 110, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelData.setFont(font)
        self.labelData.setObjectName("labelData")
        self.labelEndereco = QtWidgets.QLabel(self.centralwidget)
        self.labelEndereco.setGeometry(QtCore.QRect(20, 80, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelEndereco.setFont(font)
        self.labelEndereco.setObjectName("labelEndereco")
        self.buttonCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCadastrar.setGeometry(QtCore.QRect(240, 200, 81, 23))
        self.buttonCadastrar.setObjectName("buttonCadastrar")
        self.labelCpf = QtWidgets.QLabel(self.centralwidget)
        self.labelCpf.setGeometry(QtCore.QRect(20, 50, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelCpf.setFont(font)
        self.labelCpf.setObjectName("labelCpf")
        self.lineEndereco = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEndereco.setGeometry(QtCore.QRect(90, 80, 231, 20))
        self.lineEndereco.setObjectName("lineEndereco")
        self.lineCpf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineCpf.setGeometry(QtCore.QRect(60, 50, 261, 20))
        self.lineCpf.setObjectName("lineCpf")
        self.labelSenha = QtWidgets.QLabel(self.centralwidget)
        self.labelSenha.setGeometry(QtCore.QRect(20, 170, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.labelSenha.setFont(font)
        self.labelSenha.setObjectName("labelSenha")
        self.lineNome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineNome.setGeometry(QtCore.QRect(70, 20, 251, 20))
        self.lineNome.setObjectName("lineNome")
        self.lineSenha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSenha.setGeometry(QtCore.QRect(70, 170, 251, 20))
        self.lineSenha.setReadOnly(False)
        self.lineSenha.setObjectName("lineSenha")
        self.buttonVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonVoltar.setGeometry(QtCore.QRect(150, 200, 81, 23))
        self.buttonVoltar.setObjectName("buttonVoltar")
        self.lineData = QtWidgets.QLineEdit(self.centralwidget)
        self.lineData.setGeometry(QtCore.QRect(160, 110, 161, 20))
        self.lineData.setObjectName("lineData")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelNome.setText(_translate("MainWindow", "Nome:"))
        self.labelData.setText(_translate("MainWindow", "Data de Nascimento:"))
        self.labelEndereco.setText(_translate("MainWindow", "Endereco:"))
        self.buttonCadastrar.setText(_translate("MainWindow", "Senha"))
        self.labelCpf.setText(_translate("MainWindow", "CPF:"))
        self.labelSenha.setText(_translate("MainWindow", "Senha:"))
        self.buttonVoltar.setText(_translate("MainWindow", "Voltar"))
